services:
  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    image: abhiraj426/food-backend:latest
    container_name: food-backend
    ports:
      - "4000:4000"
    environment: 
      - MONGODB_URI=mongodb://db:27017/food-del
      # Yahan backend ke aur variables daal sakte ho agar hain toh
    depends_on:
      - db

  frontend:
    image: abhiraj426/food-frontend:latest
    container_name: food-frontend
    ports:
      - "5173:5173"
    environment:
      # Jo variables aapke .env mein the, unhe yahan aise likho:
      - VITE_API_URL=http://<YOUR_PUBLIC_IP>:4000 
    depends_on:
      - backend

volumes:
  mongo_data: