version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    image: abhiraj426/food-backend:latest
    container_name: food-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      # Agar code mein MONGO_URI hai toh yahan MONGO_URI likho
      - MONGO_URI=mongodb://db:27017/food-del
      - JWT_SECRET=mySecretKey # Agar koi aur secret hai toh wo bhi yahan daal do
    depends_on:
      - db

  frontend:
    image: abhiraj426/food-frontend:latest
    container_name: food-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      # Yahan <YOUR_PUBLIC_IP> ki jagah apne EC2 ka Public IP daalna mat bhulna
      - VITE_API_URL=http://100.53.65.52:4000
    depends_on:
      - backend

volumes:
  mongo_data: